export const images = [
  {
    id: "0",
    src: "/img/1.jpg",
    title: "Nature",
    alt: "Nice picture of Nature",
  },
  {
    id: "1",
    src: "/img/2.jpg",
    title: "Nature",
    alt: "Cool Nature",
  },
  {
    id: "2",
    src: "/img/3.jpg",
    title: "Nature",
    alt: "Great Nature",
  },
  {
    id: "3",
    src: "/img/4.jpg",
    title: "Nature",
    alt: "Amazing Nature",
  },
  {
    id: "4",
    src: "/img/5.jpg",
    title: "Nature",
    alt: "Nice Nature",
  },
  {
    id: "5",
    src: "/img/6.jpg",
    title: "Nature",
    alt: "Cozy Nature",
  },
  {
    id: "6",
    src: "/img/7.jpg",
    title: "Nature",
    alt: "Nature space",
  },
  {
    id: "7",
    src: "/img/8.jpg",
    title: "Nature",
    alt: "Favourite Nature",
  },
  {
    id: "8",
    src: "/img/9.jpg",
    title: "Nature",
    alt: "Nice image",
  },
  {
    id: "9",
    src: "/img/10.jpg",
    title: "Nature",
    alt: "Amazing Nature",
  },
  {
    id: "10",
    src: "/img/11.jpg",
    title: "Nature",
    alt: "Nice picture Nature",
  },
  {
    id: "11",
    src: "/img/12.jpg",
    title: "Nature",
    alt: "Nature picture",
  },
  {
    id: "12",
    src: "/img/13.jpg",
    title: "Nature",
    alt: "Sunny Nature",
  },
  {
    id: "13",
    src: "/img/14.jpg",
    title: "Nature",
    alt: "Nature",
  },
  {
    id: "14",
    src: "/img/15.jpg",
    title: "Nature",
    alt: "My Nature",
  },
  {
    id: "15",
    src: "/img/16.jpg",
    title: "Nature",
    alt: "Nature for work",
  },
  // {
  //   id: "16",
  //   src: "/img/17.jpg",
  //   title: "Cityscape",
  //   alt: "City to live in",
  // },
  // {
  //   id: "17",
  //   src: "/img/18.jpg",
  //   title: "Cityscape",
  //   alt: "Young city",
  // },
  // {
  //   id: "18",
  //   src: "/img/19.jpg",
  //   title: "Mountains",
  //   alt: "Nice picture of mountains",
  // },
  // {
  //   id: "19",
  //   src: "/img/20.jpg",
  //   title: "Mountains",
  //   alt: "Picture of mountains",
  // },
];

// --------------

// export const images = [
//   {
//     id: "0",
//     src: "https://images.unsplash.com/photo-1458668383970-8ddd3927deed",
//     title: "Mountains",
//     alt: "Nice picture of mountains",
//   },
//   {
//     id: "1",
//     src: "https://images.unsplash.com/photo-1494976388531-d1058494cdd8",
//     title: "Automobile",
//     alt: "Cool car",
//   },
//   {
//     id: "2",
//     src: "https://images.unsplash.com/photo-1466970601638-4e5fb6556584",
//     title: "Mountains",
//     alt: "Great mountains",
//   },
//   {
//     id: "3",
//     src: "https://images.unsplash.com/photo-1472396961693-142e6e269027",
//     title: "Mountains",
//     alt: "Amazing mountains",
//   },
//   {
//     id: "4",
//     src: "https://images.unsplash.com/photo-1485965120184-e220f721d03e",
//     title: "Bicycle",
//     alt: "Nice bike",
//   },
//   {
//     id: "5",
//     src: "https://images.unsplash.com/photo-1487017159836-4e23ece2e4cf",
//     title: "Office",
//     alt: "Cozy office",
//   },
//   {
//     id: "6",
//     src: "https://images.unsplash.com/photo-1532103054090-3491f1a05d0d",
//     title: "Office",
//     alt: "Office space",
//   },
//   {
//     id: "7",
//     src: "https://images.unsplash.com/photo-1599033153041-e88627ca70bb",
//     title: "Cityscape",
//     alt: "Favourite city",
//   },
//   {
//     id: "8",
//     src: "https://images.unsplash.com/photo-1507097634215-e82e6b518529",
//     title: "Cityscape",
//     alt: "Nice city",
//   },
//   {
//     id: "9",
//     src: "https://images.unsplash.com/photo-1458668383970-8ddd3927deed",
//     title: "Mountains",
//     alt: "High Mountains",
//   },
//   {
//     id: "10",
//     src: "https://images.unsplash.com/photo-1528988719300-046ff7faf8cb",
//     title: "Mountains",
//     alt: "Nice picture Mountains",
//   },
//   {
//     id: "11",
//     src: "https://images.unsplash.com/photo-1472396961693-142e6e269027",
//     title: "Mountains",
//     alt: "Mountains picture",
//   },
//   {
//     id: "12",
//     src: "https://images.unsplash.com/photo-1500375592092-40eb2168fd21",
//     title: "Mountains",
//     alt: "Sunny Mountains",
//   },
//   {
//     id: "13",
//     src: "https://images.unsplash.com/photo-1506744038136-46273834b3fb",
//     title: "Mountains",
//     alt: "Mountains",
//   },
//   {
//     id: "14",
//     src: "https://images.unsplash.com/photo-1487017159836-4e23ece2e4cf",
//     title: "Office",
//     alt: "My office",
//   },
//   {
//     id: "15",
//     src: "https://images.unsplash.com/photo-1532103054090-3491f1a05d0d",
//     title: "Office",
//     alt: "Office for work",
//   },
//   {
//     id: "16",
//     src: "https://images.unsplash.com/photo-1599033153041-e88627ca70bb",
//     title: "Cityscape",
//     alt: "City to live in",
//   },
//   {
//     id: "17",
//     src: "https://images.unsplash.com/photo-1494475673543-6a6a27143fc8",
//     title: "Cityscape",
//     alt: "Young city",
//   },
//   {
//     id: "18",
//     src: "https://images.unsplash.com/photo-1528988719300-046ff7faf8cb",
//     title: "Mountains",
//     alt: "Nice picture of mountains",
//   },
//   {
//     id: "19",
//     src: "https://images.unsplash.com/photo-1466970601638-4e5fb6556584",
//     title: "Mountains",
//     alt: "Picture of mountains",
//   },
// ];
